name: ref
channels:
  - defaults
  - conda-forge
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libcxx=19.1.3
  - libedit=3.1.20191231
  - libffi=3.4.4
  - libsodium=1.0.20
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.4.0
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.10.15
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024b
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.11.0
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - cachetools==5.5.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - cloudpickle==3.1.0
      - dataclasses-json==0.5.14
      - defusedxml==0.7.1
      - distro==1.9.0
      - docopt==0.6.2
      - et-xmlfile==2.0.0
      - faiss-cpu==1.9.0.post1
      - fastjsonschema==2.21.1
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - h11==0.14.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - huggingface-hub==0.26.2
      - idna==3.10
      - ipython==8.12.3
      - jinja2==3.1.4
      - jiter==0.8.0
      - joblib==1.2.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyterlab-pygments==0.3.0
      - langchain==0.0.162
      - langsmith==0.1.143
      - markupsafe==3.0.2
      - marshmallow==3.23.1
      - mistune==3.0.2
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - nbclient==0.10.1
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - numexpr==2.10.1
      - numpy==1.26.4
      - openai==1.57.0
      - openapi-schema-pydantic==1.2.4
      - openpyxl==3.1.5
      - orjson==3.10.11
      - pandas==1.5.3
      - pandocfilters==1.5.1
      - pipreqs==0.5.0
      - propcache==0.2.0
      - pydantic==1.10.19
      - pydantic-core==2.23.4
      - pyjwt==2.8.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.0
      - pytz==2024.2
      - pyyaml==6.0.2
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rpds-py==0.22.3
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.36
      - tenacity==8.2.2
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tiktoken==0.4.0
      - tinycss2==1.4.0
      - tokenizers==0.13.3
      - tqdm==4.67.0
      - transformers==4.28.1
      - typing-inspect==0.9.0
      - urllib3==2.2.3
      - webencodings==0.5.1
      - wikipedia==1.4.0
      - yarg==0.1.9
      - yarl==1.17.1
      - zhipuai==2.1.5.20230904
